# Generated by Django 4.1.3 on 2023-01-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-timestamp']},
        ),
    ]
