# Generated by Django 2.2.7 on 2020-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200106_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='project',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
