# Generated by Django 2.2.7 on 2020-01-09 21:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200106_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
