# Generated by Django 2.0.2 on 2020-11-21 20:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201121_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
