# Generated by Django 2.0.2 on 2020-11-21 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20201121_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
