# Generated by Django 4.1.3 on 2023-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
