# Generated by Django 2.2.7 on 2020-01-09 20:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200109_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
