# Generated by Django 4.1.3 on 2023-01-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
